// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Arif Hossain",
    email: "arif.hossain@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Rakib Hasan",
    email: "rakib.hasan@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Mitu Akter",
    email: "mitu.akter@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Farhana Islam",
    email: "farhana.islam@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Shakil Ahmed",
    email: "shakil.ahmed@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Sadia Rahman",
    email: "sadia.rahman@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Imran Kabir",
    email: "imran.kabir@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Mehedi Hasan",
    email: "mehedi.hasan@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Arif Hossain",
    email: "arif.hossain@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Rakib Hasan",
    email: "rakib.hasan@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Mitu Akter",
    email: "mitu.akter@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Farhana Islam",
    email: "farhana.islam@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Shakil Ahmed",
    email: "shakil.ahmed@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Sadia Rahman",
    email: "sadia.rahman@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Imran Kabir",
    email: "imran.kabir@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Mehedi Hasan",
    email: "mehedi.hasan@schoolbd.edu",
    photo: "",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Arif Hossain",
    students: ["Ayesha Siddika"],
    email: "arif.hossain@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 2,
    name: "Nusrat Jahan",
    students: ["Rafiul Islam"],
    email: "nusrat.jahan@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 3,
    name: "Tanvir Ahmed",
    students: ["Nabila Noor"],
    email: "tanvir.ahmed@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 4,
    name: "Rakib Hasan",
    students: ["Tasin Chowdhury", "Samiul Bari"],
    email: "rakib.hasan@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 5,
    name: "Mitu Akter",
    students: ["Priyanka Das"],
    email: "mitu.akter@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 6,
    name: "Farhana Islam",
    students: ["Nafiz Rahman"],
    email: "farhana.islam@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 7,
    name: "Shakil Ahmed",
    students: ["Lamia Sultana", "Tuba Akter"],
    email: "shakil.ahmed@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 8,
    name: "Sadia Rahman",
    students: ["Ridwan Karim"],
    email: "sadia.rahman@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 9,
    name: "Imran Kabir",
    students: ["Mahrin Islam", "Jannatul Ferdous"],
    email: "imran.kabir@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
  {
    id: 10,
    name: "Mehedi Hasan",
    students: ["Adiba Anjum"],
    email: "mehedi.hasan@familybd.com",
    phone: "1234567890",
    address: "House 12, Road 5, Dhanmondi, Dhaka, Bangladesh",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Sharmeen Akter", "Rezaul Karim"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Sabbir Hossain", "Tanjina Sultana"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Nigar Sultana", "Jubayer Alam"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Mosharraf Hossain", "Rumana Akter"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Fahim Ahsan", "Rupa Sarker"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Naimul Haque", "Mousumi Akter"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Sanjida Islam", "Ferdousi Rahman"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Shila Akhter", "Nafisa Karim"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Salma Yasmin", "Tahmina Akter"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Mahmudul Hasan", "Anik Barua"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Mahbub Alam",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Shahin Miah",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Kamal Uddin",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Rashedul Islam",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Rehana Begum",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Sharmin Akter",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Asaduzzaman Noor",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Biplob Roy",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Tanmoy Das",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Nargis Sultana",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Jahid Hasan",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rokeya Begum",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Momena Akter",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Selim Reza",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Rina Akter",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Shamima Sultana",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Golam Mostafa",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Sumaiya Akter",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Mizanur Rahman",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Jannatul Naima",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Kaniz Fatema",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Saiful Islam",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Nasrin Akter",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Abdur Rahim",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Shahana Parvin",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Jahangir Alam",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Lutfun Nahar",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Aminul Haque",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Roksana Yasmin",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Partha Saha",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Rafiqul Islam",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Shuvo Biswas",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Ishrat Jahan",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Kazi Maruf",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Pritam Dey",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Tahsin Ara",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Monir Hossain",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Masud Rana",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Nayeem Hasan",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Prosenjit Paul",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Arif Hossain",
    student: "Arif Hossain",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];

// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];
